=== MarcosMirandaDam/JAXBTemperaturasRepasoExamen/xml-resources/jaxb/bindingTemperaturas/iOTTemperatures.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2023 (x64) (http://www.altova.com) by  (IES Juan Jose Calvo Miguel) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified" attributeFormDefault="unqualified" vc:minVersion="1.1">
	<xs:element name="dataTemSystem">
		<xs:annotation>
			<xs:documentation>Data temp stations</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="owner" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="ownerID" type="xs:string"/>
							<xs:element name="name" type="xs:string"/>
							<xs:element name="email" type="xs:string"/>
							<xs:element name="phone" type="xs:string"/>
							<xs:element name="sensor" type="sensorType"/>
							<xs:element name="country"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="serverRegion" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="serverRegionName" type="xs:string"/>
							<xs:element name="sensor" type="sensorType" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="sensorModel" type="sensorModelType" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="sensorType">
		<xs:sequence>
			<xs:element name="sensorID" type="xs:integer"/>
			<xs:element name="ownerID" type="xs:integer"/>
			<xs:element name="modelCode" type="xs:string"/>
			<xs:element name="data" type="dataType" maxOccurs="unbounded"/>
			<xs:element name="location" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="dataType">
		<xs:sequence>
			<xs:element name="date" type="xs:date"/>
			<xs:element name="year" type="xs:integer"/>
			<xs:element name="temperature" type="xs:float"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="sensorModelType">
		<xs:sequence>
			<xs:element name="modelCode" type="xs:string"/>
			<xs:element name="modelName" type="xs:string"/>
			<xs:element name="manufacturer" type="xs:string"/>
			<xs:element name="minTemperatureRange" type="xs:float"/>
			<xs:element name="maxTemperatureRange" type="xs:float"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== MarcosMirandaDam/JAXBTemperaturasRepasoExamen/temperatures.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2023 (x64) (http://www.altova.com)-->
<dataTemSystem xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="iOTTemperatures.xsd">
	<sensorModels>
		<sensorModel>
			<modelCode>String</modelCode>
			<modelName>String</modelName>
			<manufacturer>String</manufacturer>
			<minTemperatureRange>3.141590118408203125</minTemperatureRange>
			<maxTemperatureRange>3.141590118408203125</maxTemperatureRange>
		</sensorModel>
		<sensorModel>
			<modelCode>String</modelCode>
			<modelName>String</modelName>
			<manufacturer>String</manufacturer>
			<minTemperatureRange>3.141590118408203125</minTemperatureRange>
			<maxTemperatureRange>3.141590118408203125</maxTemperatureRange>
		</sensorModel>
	</sensorModels>
	<serverRegions>
		<serverRegion>
			<serverRegionName>String</serverRegionName>
			<sensor>
				<sensorID>0</sensorID>
				<ownerID>0</ownerID>
				<modelCode>String</modelCode>
				<data>
					<date>1957-08-13</date>
					<year>0</year>
					<temperature>3.141590118408203125</temperature>
				</data>
				<data>
					<date>1957-08-13</date>
					<year>0</year>
					<temperature>3.141590118408203125</temperature>
				</data>
				<location>String</location>
			</sensor>
			<sensor>
				<sensorID>0</sensorID>
				<ownerID>0</ownerID>
				<modelCode>String</modelCode>
				<data>
					<date>1957-08-13</date>
					<year>0</year>
					<temperature>3.141590118408203125</temperature>
				</data>
				<data>
					<date>1957-08-13</date>
					<year>0</year>
					<temperature>3.141590118408203125</temperature>
				</data>
				<location>String</location>
			</sensor>
		</serverRegion>
		<serverRegion>
			<serverRegionName>String</serverRegionName>
			<sensor>
				<sensorID>0</sensorID>
				<ownerID>0</ownerID>
				<modelCode>String</modelCode>
				<data>
					<date>1957-08-13</date>
					<year>0</year>
					<temperature>3.141590118408203125</temperature>
				</data>
				<data>
					<date>1957-08-13</date>
					<year>0</year>
					<temperature>3.141590118408203125</temperature>
				</data>
				<location>String</location>
			</sensor>
			<sensor>
				<sensorID>0</sensorID>
				<ownerID>0</ownerID>
				<modelCode>String</modelCode>
				<data>
					<date>1957-08-13</date>
					<year>0</year>
					<temperature>3.141590118408203125</temperature>
				</data>
				<data>
					<date>1957-08-13</date>
					<year>0</year>
					<temperature>3.141590118408203125</temperature>
				</data>
				<location>String</location>
			</sensor>
		</serverRegion>
	</serverRegions>
	<owners>
		<owner>
			<ownerID>String</ownerID>
			<name>String</name>
			<email>String</email>
			<phone>String</phone>
			<sensor>
				<sensorID>0</sensorID>
				<ownerID>0</ownerID>
				<modelCode>String</modelCode>
				<data>
					<date>1957-08-13</date>
					<year>0</year>
					<temperature>3.141590118408203125</temperature>
				</data>
				<data>
					<date>1957-08-13</date>
					<year>0</year>
					<temperature>3.141590118408203125</temperature>
				</data>
				<location>String</location>
			</sensor>
			<country>text</country>
		</owner>
		<owner>
			<ownerID>String</ownerID>
			<name>String</name>
			<email>String</email>
			<phone>String</phone>
			<sensor>
				<sensorID>0</sensorID>
				<ownerID>0</ownerID>
				<modelCode>String</modelCode>
				<data>
					<date>1957-08-13</date>
					<year>0</year>
					<temperature>3.141590118408203125</temperature>
				</data>
				<data>
					<date>1957-08-13</date>
					<year>0</year>
					<temperature>3.141590118408203125</temperature>
				</data>
				<location>String</location>
			</sensor>
			<country>text</country>
		</owner>
	</owners>
</dataTemSystem>
